### PR TITLE
Plugin version raised

### PR DESCRIPTION
**Pull request by ivmarkov**

### CODE REVIEW

**Comment by branflake2267** [comment]
Cool :)

**Comment by ivmarkov** [comment]
Note that in the new GWT Plugin, ideally, you should depend on SDBG 1.0.10 or later. I'll build the new SDBG release now and will push it to the BETA SDBG repo (http://sdbg.github.io/p2beta/)

**Comment by branflake2267** [comment]
Thanks, I can try that out. Another note, I submitted to the marketplace with the default repo, as an optionally selected item.

**Comment by branflake2267** [comment]
That means I submitted as a secondary item of the GWT Eclipse Plugin.

**Comment by branflake2267** [comment]
screen shot 2016-10-08 at 8 58 02 am

**Comment by ivmarkov** [comment]
The new SDFBG plugin is available here: http://sdbg.github.io/p2beta/
If possible, please test before I push this release to the official p2 repo (http://sdbg.github.io/p2/)

**Comment by branflake2267** [comment]
I'll do that today. I've already tested it with debugger, and it works great. I'll be testing more today. Thanks for working this in and getting things worked out. Nice job!

**Pull request merged**
