### PR TITLE
GWT Eclipse Plugin v3 testing

### PR DESCRIPTION
**Pull request by branflake2267**
I'm trying to work up the integration for GWT Eclipse Plugin V3. Although for some reason I can't get it to mirror yet, so something is out of sync. I'm pulling for notification. Don't merge. I'm using a build server internally to deploy to the cloud storage for testing integration.

### CODE REVIEW

**Comment by branflake2267** [comment]
I couldn't get copying from the mirror to work for me, probably b/c I'm missing something. Although I tried setting up a feature and it works good. https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/202 I'd like to find out if this is going to concern you or be a problem. I'm aiming for providing an EA for the GWT Eclipse Plugin by GWTCon. Let me know what you thing, thanks. I'm open to options...

**Comment by branflake2267** [comment]
screen shot 2016-09-25 at 9 14 39 pm

**Comment by ivmarkov** [comment]
I think these are the main changes in your pull request:
# Raising of the Java SE build environment from 1.6 to 1.7 (which is fine, I agree)
# Replacement - in all MANIFEST.MFs - of 
## What is the reason for that?
`-Bundle-Version: 1.0.9.qualifier` with `+Bundle-Version: 0.0.0.qualifier`
# Replacement - in all pom.xmls - of
`<version>1.0.9.qualifier</version>` with `<version>0.0.0-SNAPSHOT</version>` 
## what is the reason for that too?
# Introduction of shell scripts, which - if I'm not mistaken - upload the p2 repo to Google Cloud. What is the reason for that? Have in mind, that there is already a p2 repo for SDBG, gosted in GitHub itself.
# Upping the Eclipse requirements level from Luna to Mars. Is there any reason why you would like SDBG to depend on the Mars release?

**Comment by branflake2267** [comment]
Replacement - in all MANIFEST.MFs - of -Bundle-Version: 1.0.9.qualifier with +Bundle-Version: 0.0.0.qualifier. What is the reason for that?
- This was just a quick change so I could test. I have was issues with building, so I reset the version to match the plugin qualifiers. I think maven or tycho has a release cycle to update the versions. 

Replacement - in all pom.xmls - of <version>1.0.9.qualifier</version> with <version>0.0.0-SNAPSHOT</version>. What is the reason for that too?
- Matching the plugin qualifiers was needed to build IIRC. I setup the build server to automate stuff. 

Introduction of shell scripts, which - if I'm not mistaken - upload the p2 repo to Google Cloud. What is the reason for that? Have in mind, that there is already a p2 repo for SDBG, hosted in GitHub itself.
- I use the shell scripts to upload to my repo for testing, they could be removed. I was having issues mirror

Upping the Eclipse requirements level from Luna to Mars. Is there any reason why you would like SDBG to depend on the Mars release?
- For GWT Eclipse Plugin V3, I plan on supporting only neon forward. I've got it set to mars, but will have to fix a couple things to increment it. GPE is getting deprecated in the 4th quarter. 

There really isn't a need for me to do any of this, although things are happening fast and I'm not sure if you have time to help upgrade the plugin to support GWT Eclipse Plugin V3. I'll start to announce the beta at GWTCon. What I'd like to see if I could make happen is distribute the SDBG with GWT Eclipse plugin if possible so we can achieve the best install path. I'll be putting the GWT Eclipse Plugin V3 in the marketplace and it'd be nice to figure out how to depend on or have SDBG get distributed with GWT Eclipse Plugin. At release time, I'll setup versioning for GWT Eclipse Plugin. I'm just proposing an option(s). Feel free to let me know what you like to do. 

If you want to keep it separate, let me know what we can do to get it upgraded to work with GWT Eclipse Plugin V3.  Hopefully, I'm not too terse at the moment, as I've got much to do before November.

**Comment by branflake2267** [comment]
I forgot, I've got more changes coming, I've renamed all the extension points from com.google to com.gwtplugins.

**Comment by ivmarkov** [comment]
Even if the GWT Plugin depends on Neon or later, SDBG can still depend on earlier Eclipse releases, or is it not the case?

Regarding "distribute the SDBG with GWT Eclipse plugin if possible" - would would be the delivery channels for the GWT Plugin? an installer/zip bundle, or just a p2 repository? If just a p2 repository, can't we somehow just make SDBG an optional dependency for the GWT Plugin? This way, when the GWT Plugin is being installed, SDBG will be selected for installation by default too, but it would still be pulled from its own p2 repository.

**Comment by branflake2267** [comment]
You're right about the release issue, I'd like to overcome that. I'm doing a copy of your p2 repo and sticking putting it in the GPE fork repo. I can copy any time things change in your repo, which isn't to often, but doesn't get tied down to another release cycle. But for some reason I wasn't able to get the copy to work, although I could see the plugins in the repo. If you don't mind me copying from your p2 repo into the GWT Eclipse repo, that's an option. Maybe there is some other technique I'm missing. I'll setup a task to explore mirroring again, and maybe other dependent (optional) ways. My overall goal is to make it super easy to get SDBG, and provide it as an option to use with GWT Eclipse Plugin V3.

**Comment by ivmarkov** [comment]
I do not understand why you are copying the SDBG plugins into your repo.
In yout GWT Plugin feature, you can simply express optional dependencies on the SDBG feature without pulling the SDBG plugins physically to your location.

**Comment by branflake2267** [comment]
I was aiming to have SDBG install option next to the GWT Eclipse Plugin during install. So instead of adding via separate install I thought I could shorten the path by providing it with the Eclipse Install. Does that help?

**Comment by ivmarkov** [comment]
What do you mean by "install"? Install from the Marketplace? Is the Eclipse Marketplace P2-based? If yes, then again: why don't you just *reference* the existing SDBG P2 repo instead of copying it? I mean, just like you reference the Eclipse plugins/features the GWT Plugin depends on. You are not copying them too in your GWT Plugin repo, right?

**Comment by branflake2267** [comment]
Figuring out SDBG is up next for me, so I'll help look into the issue. After this I'll begin the transition to an EA release, and deprecating GPE notices... I'm aiming to be finished with whatever we choose this weekend, so I can begin to write my talks next week using screenshots from the EA version. I know you're busy, so if you don't get to it, no worries, I'll either have to scrap the option, or I'll aim to push forward with an integrated option. At any rate, I'll keep the train updated if that does occur. 

I'm going to close this PR, as it's not needed.

**Comment by branflake2267** [comment]
I think I have it figured out. https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/244/files

screen shot 2016-10-04 at 10 28 29 pm

**Comment by branflake2267** [comment]
And wha tit looks like in the installer. 
screen shot 2016-10-04 at 10 43 06 pm

**Comment by ivmarkov** [comment]
Looks good to me!

**Comment by branflake2267** [comment]
Cool thanks!

**Pull request closed without merging**
