### PR TITLE
Replace GPE extension with GWT Eclipse Plugin (V3) extension.

### PR DESCRIPTION
**Pull request by branflake2267**
GPE and GPE-fork are going away in the not too distant future. Google will be announcing the new Plugins soon and deprecating GPE. I'm suggesting swap out with the new GWT Eclipse Plugin (V3). 

- Move to new plugin? 
- I didn't fix the launcher?
- some auto formatting occurred in this pr, will that be an issue? 
- Release site isn't up yet. I'm waiting for another pr to come in before I push bits.

### CODE REVIEW

**Comment by branflake2267** [comment]
Any thoughts? Should I drop, refine, or something else?

**Comment by branflake2267** [comment]
I'm prepping for release. I've got the release versioned and deployed to http://storage.googleapis.com/gwt-eclipse-plugin/v3/release

**Comment by ivmarkov** [comment]
Looks good, and I'll merge it anyway, just one question: 
In another conversation, you mentioned that you've changed the package names but not the bundle Id and the extension points. This PR looks the other way around - as if you've changed the extension points and bundle Id but not the package names?

**Comment by ivmarkov** [comment]
Reverts temporarily sdbg/sdbg#150

Problem is:
[ERROR] Failed to resolve target definition C:\Users\Ivan\git\sdbg\com.github.sd
bg.releng.targetplatform\com.github.sdbg.releng.targetplatform.target: Could not
find "com.gwtplugins.eclipse.suite.v3.feature/0.0.0" in the repositories of the
current location -> [Help 1]
[ERROR]

Are you sure you have pushed to http://storage.googleapis.com/gwt-eclipse-plugin/v3/release ?
There is no feature com.gwtplugins.eclipse.suite.v3.feature in there, it seems?

**Comment by ivmarkov** [comment]
OK, there is such a feature, I'm still investigating what is going on...

**Pull request merged**
