### PR TITLE
Removed JAXB dependency and all the unnessesary subprojects

### PR DESCRIPTION
**Pull request by keinhaar**
Removed jaxb files. Theay were only needed because of the DatatypeConverter dependency, which was removed too.

### CODE REVIEW

**Comment by ivmarkov** [comment]
I no longer actively maintain this project and not putting it in an archived state is an omissiin in my side. If you would like to take over, I can transfer you ownership.

**Comment by keinhaar** [comment]
Hi, thanks for your answer. I knew that, but i thought that there may be another maintainer.
If there is nobody else, i would be happy to accept ownership. 
Thanks for all the work you have done in this project.

Martin


Am 17. Oktober 2022 15:12:48 MESZ schrieb Ivan Markov ***@***.***>:

**Comment by keinhaar** [comment]
@ivmarkov 
Hello Ivan,
maybe you've been to busy to notice my mail.
I would like to take ownership for this project.
Could you please transfer the ownership, or at least add admin access for me?
Thanks in advance...
Martin

**Comment by ivmarkov** [comment]
@keinhaar Sorry, a bit overwhelmed recently. 
Transferring ownership would be difficult, as I need to move the two projects outside the sdbg org, which probably does not make sense. I've instead given you admin privileges.

**Comment by axeluhl** [comment]
The diff seems rather huge given the intent of the change. For example, I see many .settings files removed. Why? Also there are changes that only affect import order. I suggest to minimize the diff.

**Comment by keinhaar** [comment]
@axeluhl you are right, i will try to minimize.

**Pull request merged**
