### PR TITLE
Add java11 support

### PR DESCRIPTION
**Pull request by lglowania**
Added jaxb-libs as described by @ManfredTremmel in #161

### CODE REVIEW

**Comment by ivmarkov** [comment]
I'll be able to review in a few days. Please bear with me.

**Comment by cherio** [comment]
> I'll be able to review in a few days. Please bear with me.

Thanks for the invitation but I prefer to please bears alone )))

**Comment by jernejkubuntu** [comment]
eclipse 2020-9 will require java 11
https://ed-merks.blogspot.com/2020/08/no-java-no-problem.html

**Comment by keinhaar** [comment]
Works as expected. Please accept the pull request.
Eclipse does no longer run with jdk < 11.
A new release would be great.

**Pull request merged**
